### ISSUE TITLE
Add new vulnerabilities to database

### ISSUE THREAD

**Issue by andresriancho** [vulndb/data#17]
## Description

Using vulndb in w3af I noticed that there are some missing vulnerabilities which need to be added to the database with **low priority**
## Vulnerability list
- [ ] 'Buffer overflow vulnerability'
- [ ] 'MX injection vulnerability'
- [ ] 'Unsafe preg_replace usage'
- [ ] 'ReDoS vulnerability'
- [ ] Server side include vulnerability
- [ ] Persistent server side include vulnerability
- [x] Basic HTTP credentials
- [ ] Path disclosure vulnerability (maybe it's already in the DB?)
- [ ] Malware identified
- [ ] CSP vulnerability
- [x] Missing X-Content-Type-Options header
- [x] Guessable credentials
## Task

For each vulnerability we need to create a new JSON file inside the `db` directory (that looks like [this](https://github.com/vulndb/data/blob/master/db/17-file-inclusion.json)) and make sure it passes all the tests.
## References
- https://github.com/andresriancho/w3af/issues/9174
- https://github.com/andresriancho/w3af/blob/master/w3af/core/data/constants/vulns.py

**Comment by andresriancho** [comment]
Thanks to the amazing job from @snoopythesecuritydog we now have three more vulnerabilities in the DB!

https://github.com/vulndb/data/pull/42/files
